name: tracers-dispersion
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Base python
  - python==3.11
  # Pip dependencies
  - pip
  - pip:
    - astropy==7.2.0
    - cdasws==1.8.15
    - intervaltree==3.2.1
    - jupyterlab==4.5.5
    - matplotlib==3.10.8
    - pandas==3.0.1
    - requests==2.32.5
    - spacepy==0.7.0
    - termcolor==3.3.0
    - tqdm==4.67.3
